language: node_js
node_js:
  - "node"

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - cd ./dist/rav/ && ls -la

deploy:
  provider: surge
  project: ./dist/rav/
  domain: rav.surge.sh 