language: node_js
node_js:
  - "node"

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - ng build --prod
  - surge ./dist/rav/ rav.surge.sh

deploy:
  provider: surge
  project: ./dist/rav/
  domain: rav.surge.sh 